### ISSUE TITLE
 (entity, entity relationship, entity)? 

### ISSUE THREAD

**Issue by muqishan** [hanjiale/GenPT#3]
Hello, regarding the GenPT algorithm released by your team, I only saw the training code. In order to show the results to my partners more intuitively, I made an inference code myself. But according to the output of the model, I found that only the entity relationship is output. Can the model output a triple (entity, entity relationship, entity)? If so, what modifications do I need to make?

**Comment by hanjiale** [comment]
Hi, thanks for your interest to our work. GenPT is designed to identify relations given two entities in a sentence, not generating whole triples. If you only want to output the given two entities, you can try to insert the following codes [here](https://github.com/hanjiale/GenPT/blob/main/code/run_prompt.py#L55C1-L55C1):
```
entity_mentions = []
        for item in val_dataset.data:
            sentence = item['token']
            head_entity, tail_entity = sentence[item['subj_start']:item['subj_end']+1], sentence[item['obj_start']:item['obj_end']+1]
            entity_mentions.append([head_entity, tail_entity])
```

**Comment by muqishan** [comment]
Thanks, I newly added the NER model in combination with GenPT so that I get triples that qualify and arbitrary sentences.
